#!/bin/bash

host='' # Ex ldaps://server.com.
user='' # Usually "cn=monitor"
domain="dc=uba,dc=ar" # Ex "dc=example,dc=ar"
passwd='' 
estadlog='' # Log to be read from zabbix agent. Ex "/var/log/zabbix-agent/olmonitor.log"
#array cn=Operations
OpArray=("Modify" "Bind" "Unbind" "Add" "Delete" "Compare" "Search" "Modrdn" "Abandon" "Extended")
#array cn=Statistics
EsArray=("Bytes" "PDU" "Entries" "Referrals")
#array cn=Waiters
WaArray=("Read" "Write")

truncate -s 0 $estadlog

echo "cn=Operations per Minute and per Second" >> $estadlog
for op in ${OpArray[@]}; do
        if [ ! -z "$estadlog" ]; then
                echo "cn=$op,cn=Operations" >> $estadlog
                vnow=`ldapsearch -H $host -x -D "$user,$domain" -w "$passwd" -b "cn=$op,cn=Operations,cn=Monitor" -s sub "(objectClass=*)" + | grep "monitorOpCompleted:" | awk '{print $NF}'`
                vbefore=`grep -i "acu$op" $estadlog".prev" | awk '{print $NF}'`
                opdiffmin=$((vnow - vbefore ))
                opdiffsec=$(( (vnow - vbefore ) / 60  ))
                echo acu$op $vnow >> $estadlog
                echo ""$op"-Min" $opdiffmin >> $estadlog
                echo ""$op"-Sec" $opdiffsec >> $estadlog
                totalmin=`expr $totalmin + $opdiffmin`
                totalsec=`expr $totalsec + $opdiffmin`
        fi
done
echo "cn=Total,cn=Operations" >> $estadlog
echo "TotalOp-Sec" $totalsec >> $estadlog
echo "TotalOp-Min" $totalmin >> $estadlog

echo "cn=Statistics per Minute and per Second" >> $estadlog
for es in ${EsArray[@]}; do
        if [ ! -z "$estadlog" ]; then
                echo "cn=$es,cn=Statistics" >> $estadlog
                vnow=`ldapsearch -H $host -x -D "$user,$domain" -w "$passwd" -b "cn=$es,cn=Statistics,cn=Monitor" -s sub "(objectClass=*)" + | grep "monitorCounter:" | awk '{print $NF}'`
                vbefore=`grep -i "acu$es" $estadlog".prev" | awk '{print $NF}'`
                esdiffmin=$((vnow - vbefore))
                esdiffsec=$(( (vnow - vbefore) / 60  ))
                echo acu$es $vnow >> $estadlog
                echo ""$es"-Min" $esdiffmin >> $estadlog
                echo ""$es"-Sec" $esdiffsec >> $estadlog
        fi
done

echo "cn=Total,cn=Connections per Minute and per Second" >> $estadlog
if [ ! -z "$estadlog" ]; then
        echo "cn=Total,cn=Connections" >> $estadlog
        vnow=`ldapsearch -H $host -x -D "$user,$domain" -w "$passwd" -b "cn=Total,cn=Connections,cn=Monitor" -s sub "(objectClass=*)" + | grep "monitorCounter:" | awk '{print $NF}'`
        vbefore=`grep -i "acuTotal" $estadlog".prev" | awk '{print $NF}'`
  codiffmin=$((vnow - vbefore))
  codiffsec=$(( (vnow - vbefore) / 60  ))
  echo acuTotalCo $vnow >> $estadlog
  echo ""TotalCo"-Min" $codiffmin >> $estadlog
  echo ""TotalCo"-Sec" $codiffsec >> $estadlog
fi

echo "cn=Current,cn=Connectios" >> $estadlog
if [ ! -z "$estadlog" ]; then
        valor=`ldapsearch -H $host -x -D "$user,$domain" -w "$passwd" -b "cn=Current,cn=Connections,cn=Monitor" -s sub "(objectClass=*)" + | grep "monitorCounter:" | awk '{print $NF}'`
  echo "CurrentConnections" $valor  >> $estadlog
fi

echo "cn=Waiters,cn=Monitor per Minute and per Second" >> $estadlog
for wa in ${WaArray[@]}; do
if [ ! -z "$estadlog" ]; then
        echo "cn=$wa,cn=Connections" >> $estadlog
        vnow=`ldapsearch -H $host -x -D "$user,$domain" -w "$passwd" -b "cn=$wa,cn=Waiters,cn=Monitor" -s sub "(objectClass=*)" + | grep "monitorCounter:" | awk '{print $NF}'`
        vbefore=`grep -i "acu$wa" $estadlog".prev" | awk '{print $NF}'`
  wadiffmin=$((vnow - vbefore ))
  wadiffsec=$(( (vnow - vbefore ) / 60  ))
  echo acu$wa $vactual >> $estadlog
  echo ""$wa"-Min" $wadiffmin >> $estadlog
  echo ""$wa"-Sec" $wadiffsec >> $estadlog
fi
done

# Save last iteration
cp $estadlog $estadlog".prev"
